version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Asmterdam
    volumes:
      - ${CONF_DIR}:/config
      - ${MOVIE_DIR}:/data/movies
      - ${SERIES_DIR}:/data/tvshows
      - ${HOME_DIR}:/data/home_movies
      - ${VIV_DIR}:/data/viv-online
      - ${YOU_DIR}
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: unless-stopped
